<a href="https://colab.research.google.com/github/paolalarap/challenge_TelecomX2_palp/blob/main/Challenge_TelecomX2_palp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafío Telecom X Parte 2:


*  Objetivo Principal: Anticipar la evasión de clientes identificando quiénes están en riesgo, qué variables influyen y qué perfiles requieren mayor atención.
*   Preparación de Datos: Utilizarás los datos tratados en el Challenge anterior, realizando preparaciones adicionales para modelos predictivos, como eliminar columnas irrelevantes y normalizar datos.
  https://github.com/paolalarap/challenge_TelecomX_palp.git

In [10]:
import pandas as pd

## **Preparación de los datos**

a) Extracción de archivo del desafío anterior

In [11]:
url='https://raw.githubusercontent.com/paolalarap/challenge_TelecomX2_palp/refs/heads/main/datos_clientes.csv'

In [12]:
datos_clientes=pd.read_csv(url)

In [13]:
datos_clientes.head()

,id_cliente,cancelacion,cliente.genero,cliente.ciudadano_senior,cliente.pareja,cliente.dependientes,cliente.antiguedad,telefono.servicio_telefonico,telefono.lineas_multiples,internet.servicio_internet,...,internet.proteccion_dispositivo,internet.soporte_tecnico,internet.tv_streaming,internet.peliculas_streaming,cuenta.contrato,cuenta.facturacion_sin_papel,cuenta.metodo_pago,cuenta.cargos_mensuales,cuenta.cargos_totales,cuenta_diaria
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40,2.796667

b) Eliminación de Columnas Irrelevantes

In [14]:
datos_clientes = datos_clientes[datos_clientes["cancelacion"].notna()]
datos_clientes= datos_clientes[datos_clientes["cancelacion"].str.strip() != ""]

In [15]:
datos_clientes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_cliente                       7043 non-null   object
 1   cancelacion                      7043 non-null   object
 2   cliente.genero                   7043 non-null   object
 3   cliente.ciudadano_senior         7043 non-null   int64
 4   cliente.pareja                   7043 non-null   object
 5   cliente.dependientes             7043 non-null   object
 6   cliente.antiguedad               7043 non-null   int64
 7   telefono.servicio_telefonico     7043 non-null   object
 8   telefono.lineas_multiples        7043 non-null   object
 9   internet.servicio_internet       7043 non-null   object
 10  internet.seguridad_en_linea      7043 non-null   object
 11  internet.copia_seguridad         7043 non-null   object
 12  internet.proteccion_dispositivo  7043 non-null   object
 13  internet.soporte_tecnico         7043 non-null   object
 14  internet.tv_streaming            7043 non-null   object
 15  internet.peliculas_streaming     7043 non-null   object
 16  cuenta.contrato                  7043 non-null   object
 17  cuenta.facturacion_sin_papel     7043 non-null   object
 18  cuenta.metodo_pago               7043 non-null   object
 19  cuenta.cargos_mensuales          7043 non-null   float64
 20  cuenta.cargos_totales            7032 non-null   float64
 21  cuenta_diaria                    7043 non-null   float64
dtypes: float64(3), int64(2), object(17)
memory usage: 1.2+ MB

In [20]:
# Eliminación de columnas
columnas_eliminar = [
    'id_cliente',
    'cliente.genero',
    'telefono.servicio_telefonico',
    'telefono.lineas_multiples',
    'internet.copia_seguridad',
    'internet.proteccion_dispositivo',
    'internet.peliculas_streaming',
    'cuenta.facturacion_sin_papel'
]

datos_clientes= datos_clientes.drop(columns=columnas_eliminar, errors='ignore')

In [17]:
datos_clientes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   cancelacion                  7043 non-null   object
 1   cliente.ciudadano_senior     7043 non-null   int64
 2   cliente.pareja               7043 non-null   object
 3   cliente.dependientes         7043 non-null   object
 4   cliente.antiguedad           7043 non-null   int64
 5   internet.servicio_internet   7043 non-null   object
 6   internet.seguridad_en_linea  7043 non-null   object
 7   internet.soporte_tecnico     7043 non-null   object
 8   internet.tv_streaming        7043 non-null   object
 9   cuenta.contrato              7043 non-null   object
 10  cuenta.metodo_pago           7043 non-null   object
 11  cuenta.cargos_mensuales      7043 non-null   float64
 12  cuenta.cargos_totales        7032 non-null   float64
 13  cuenta_diaria                7043 non-null   float64
dtypes: float64(3), int64(2), object(9)
memory usage: 825.4+ KB

In [24]:
datos_clientes.head()

,cancelacion,cliente.ciudadano_senior,cliente.pareja,cliente.dependientes,cliente.antiguedad,internet.servicio_internet,internet.seguridad_en_linea,internet.soporte_tecnico,internet.tv_streaming,cuenta.contrato,cuenta.metodo_pago,cuenta.cargos_mensuales,cuenta.cargos_totales,cuenta_diaria
0,No,0,Yes,Yes,9,DSL,No,Yes,Yes,One year,Mailed check,65.6,593.30,2.186667
1,No,0,No,No,9,DSL,No,No,No,Month-to-month,Mailed check,59.9,542.40,1.996667
2,Yes,0,No,No,4,Fiber optic,No,No,No,Month-to-month,Electronic check,73.9,280.85,2.463333
3,Yes,1,Yes,No,13,Fiber optic,No,No,Yes,Month-to-month,Electronic check,98.0,1237.85,3.266667
4,Yes,1,Yes,No,3,Fiber optic,No,Yes,Yes,Month-to-month,Mailed check,83.9,267.40,2.796667

c) Encoding

In [25]:
# Seleccionar columnas categóricas automáticamente
columnas_categoricas = datos_clientes.select_dtypes(include=['object']).columns

# Aplicar One-Hot Encoding con get_dummies
datos_clientes_codificado = pd.get_dummies(
    datos_clientes,
    columns=columnas_categoricas,
    drop_first=True
)

In [26]:
datos_clientes_codificado.head()

,cliente.ciudadano_senior,cliente.antiguedad,cuenta.cargos_mensuales,cuenta.cargos_totales,cuenta_diaria,cancelacion_Yes,cliente.pareja_Yes,cliente.dependientes_Yes,internet.servicio_internet_Fiber optic,internet.servicio_internet_No,...,internet.seguridad_en_linea_Yes,internet.soporte_tecnico_No internet service,internet.soporte_tecnico_Yes,internet.tv_streaming_No internet service,internet.tv_streaming_Yes,cuenta.contrato_One year,cuenta.contrato_Two year,cuenta.metodo_pago_Credit card (automatic),cuenta.metodo_pago_Electronic check,cuenta.metodo_pago_Mailed check
0,0,9,65.6,593.30,2.186667,False,True,True,False,False,...,False,False,True,False,True,True,False,False,False,True
1,0,9,59.9,542.40,1.996667,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,0,4,73.9,280.85,2.463333,True,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,13,98.0,1237.85,3.266667,True,True,False,True,False,...,False,False,False,False,True,False,False,False,True,False
4,1,3,83.9,267.40,2.796667,True,True,False,True,False,...,False,False,True,False,True,False,False,False,False,True

In [28]:
datos_clientes_codificado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cliente.ciudadano_senior                         7043 non-null   int64
 1   cliente.antiguedad                               7043 non-null   int64
 2   cuenta.cargos_mensuales                          7043 non-null   float64
 3   cuenta.cargos_totales                            7032 non-null   float64
 4   cuenta_diaria                                    7043 non-null   float64
 5   cancelacion_Yes                                  7043 non-null   bool
 6   cliente.pareja_Yes                               7043 non-null   bool
 7   cliente.dependientes_Yes                         7043 non-null   bool
 8   internet.servicio_internet_Fiber optic           7043 non-null   bool
 9   internet.servicio_internet_No                    7043 non-null   bool
 10  internet.seguridad_en_linea_No internet service  7043 non-null   bool
 11  internet.seguridad_en_linea_Yes                  7043 non-null   bool
 12  internet.soporte_tecnico_No internet service     7043 non-null   bool
 13  internet.soporte_tecnico_Yes                     7043 non-null   bool
 14  internet.tv_streaming_No internet service        7043 non-null   bool
 15  internet.tv_streaming_Yes                        7043 non-null   bool
 16  cuenta.contrato_One year                         7043 non-null   bool
 17  cuenta.contrato_Two year                         7043 non-null   bool
 18  cuenta.metodo_pago_Credit card (automatic)       7043 non-null   bool
 19  cuenta.metodo_pago_Electronic check              7043 non-null   bool
 20  cuenta.metodo_pago_Mailed check                  7043 non-null   bool
dtypes: bool(16), float64(3), int64(2)
memory usage: 440.2 KB